apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-deployment1
  labels:
    app: custom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom
  template:
    metadata:
      labels:
        app: custom
    spec:
      containers:
      - name: custom
        image: shivamitta/myfirstrepo
        ports:
        - containerPort: 80
